export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_TITLE_SURVEY = "SET_TITLE_SURVEY";
export const SET_SURVEY_CATEGORY = "SET_SURVEY_CATEGORY";
export const SAVE_MULTICHOICE_STATE = "SAVE_MULTICHOICE_STATE";
export const SAVE_SINGLETEXTBOX_STATE = "SAVE_SINGLETEXTBOX_STATE";
export const SET_MULTICHOICE_INPUTSTATE = "SET_MULTICHOICE_INPUTSTATE";
export const SET_MULTICHOICE_ID = "SET_MULTICHOICE_ID";