export const SURVEY_CATEGORY = "SURVEY_CATEGORY";
export const SURVEY_TITLE = "SURVEY_TITLE";
export const SURVEY_FORM_BUILDER = "SURVEY_FORM_BUILDER";
export const SURVEY_CATEGORY_BUILDER = "SURVEY_CATEGORY_BUILDER";
export const SURVEY_FORM_QUESTION = "SURVEY_FORM_QUESTION";
export const SURVEY_FORM_COPIED = "SURVEY_FORM_COPIED";
export const SURVEY_TYPE_QUESTION = "SURVEY_TYPE_QUESTON";
export const SURVEY_CAN_EDIT = "SURVEY_CAN_EDIT";
export const SURVEY_EDIT_TYPE_QUESTION = "SURVEY_EDIT_TYPE_QUESTION";
export const TYPE_QUESTION = {
  SHORT: "SHORT",
  LONG: "LONG",
  MULTIPLE: "MULTIPLE",
  CHECKBOX: "CHECKBOX",
  STAR: "START",
  DROPDOWNFORMAT: "DROPDOWNFORMAT",
  SINGLETEXTBOX: "SHORT",
  MULTIPLETEXTBOX: "MULTIPLETEXTBOX",
  TEXTFORMAT: "TEXTFORMAT",
  RANKING: "RANKING",
  DATEANDTIME: "DATEANDTIME",
  COMMENTBOX: "COMMENTBOX",
};
export const TYPE_BUTTON = {
  OK: "OK",
  PLUS: "PLUS",
};

export const DESCRIPTION_HEADER = {
  EDIT: "EDIT",
  SAVE: "SAVE",
};

export const MULTICHOICE = {
  INPUTSTATE: "INPUTSTATE",
  MULTICHOICEID: "MULTICHOICEID",
  SELF: "SELF",
  EDITMULTICHOICE: "EDITMULTICHOICE",
};

export const FORM_ELEMENT = {
  MULTICHOICEV2: "MULTICHOICEV2",
};

export const RESULT_ACTION = {
  COPY: "COPY",
  EDIT: "EDIT",
};

export const LOADER = "LOADER";
