export const SURVEY_CATEGORY = "SURVEY_CATEGORY";
export const SURVEY_TITLE = "SURVEY_TITLE";
export const SURVEY_FORM_BUILDER = "SURVEY_FORM_BUILDER";
export const SURVEY_CATEGORY_BUILDER = "SURVEY_CATEGORY_BUILDER";
export const SURVEY_FORM_QUESTION = "SURVEY_FORM_QUESTION";
export const SURVEY_FORM_COPIED = "SURVEY_FORM_COPIED";
export const SURVEY_TYPE_QUESTION = "SURVEY_TYPE_QUESTON";
export const SURVEY_CAN_EDIT = "SURVEY_CAN_EDIT";
export const USER = "USER";
export const SURVEY_EDIT_TYPE_QUESTION = "SURVEY_EDIT_TYPE_QUESTION";
export const SURVEY_LOGO = "SURVEY_LOGO";
export const SURVEY_LIST = {
  FETCH_SURVEY_LIST: "FETCH_SURVEY_LIST",
  SURVEY_LIST_SUCCESS: "SUCCESS",
  SURVEY_LIST_ERROR: "ERROR",
  SURVEY_SUCCESS: "SURVEY_SUCCESS",
  SURVEY_ERROR: "SURVEY_ERROR",
  EDIT_SUCCESS: "EDIT_SUCCESS",
  EDIT_ERROR: "EDIT_ERROR",
};
export const MESSAGE = {
  WARNING: "WARNING",
  FAILED: "FAILED",
  SUCCESS: "SUCCESS",
  STATUS: "STATUS",
};
export const SURVEY_HEADER = {
  TITLE: "SURVEY_HEADER_TITLE",
  DESC: "SURVEY_HEADER_DESC",
};
export const TYPE_QUESTION = {
  SHORT: "SHORT",
  LONG: "LONG",
  MULTIPLE: "MULTIPLE",
  CHECKBOX: "CHECKBOX",
  STAR: "START",
  DROPDOWNFORMAT: "DROPDOWNFORMAT",
  SINGLETEXTBOX: "SHORT",
  MULTIPLETEXTBOX: "MULTIPLETEXTBOX",
  TEXTFORMAT: "TEXTFORMAT",
  RANKING: "RANKING",
  DATEANDTIME: "DATEANDTIME",
  COMMENTBOX: "COMMENTBOX",
};
export const TYPE_BUTTON = {
  OK: "OK",
  PLUS: "PLUS",
};

export const DESCRIPTION_HEADER = {
  EDIT: "EDIT",
  SAVE: "SAVE",
};

export const MULTICHOICE = {
  INPUTSTATE: "INPUTSTATE",
  MULTICHOICEID: "MULTICHOICEID",
  SELF: "SELF",
  EDITMULTICHOICE: "EDITMULTICHOICE",
};

export const FORM_ELEMENT = {
  MULTICHOICEV2: "MULTICHOICEV2",
};

export const RESULT_ACTION = {
  COPY: "COPY",
  EDIT: "EDIT",
};

export const LOADER = "LOADER";
export const MESSAGE_PROMPT = "MESSAGE_PROMPT";
