export const SURVEY_CATEGORY = "SURVEY_CATEGORY";
export const SURVEY_TITLE = "SURVEY_TITLE";
export const SURVEY_FORM_BUILDER = "SURVEY_FORM_BUILDER";
export const SURVEY_CATEGORY_BUILDER = "SURVEY_CATEGORY_BUILDER";
export const TYPE_QUESTION = {
    SHORT: 'SHORT',
    LONG: 'LONG',
    MULTIPLE: 'MULTIPLE',
    CHECKBOX: 'CHECKBOX',
    STAR: 'START',
    DROPDOWNFORMAT: 'DROPDOWNFORMAT',
    SINGLETEXTBOX: 'SHORT',
    MULTIPLETEXTBOX: 'MULTIPLETEXTBOX',
    TEXTFORMAT: 'TEXTFORMAT',
    RANKING: 'RANKING',
    DATEANDTIME: 'DATEANDTIME',
    COMMENTBOX: 'COMMENTBOX'
}
export const TYPE_BUTTON = {
    OK: 'OK',
    PLUS: 'PLUS'
}